### ISSUE TITLE
Asset 596: bad answer ID for thrombin, duplicate of 595?

### ISSUE THREAD

**Issue by colleenXu** [NCATSTranslator/Tests#86] opened 2024-06-28 07:35 UTC
Similar to 503 https://github.com/NCATSTranslator/Tests/issues/83...

> [This asset](https://github.com/NCATSTranslator/Tests/blob/main/test_assets/Asset_596.json) says the expected output name is `UNIPROTKB:P00734`, which is the gene F2 + its proteins ([Dev NodeNorm](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=UNIPROTKB:P00734&conflate=true&drug_chemical_conflate=true&description=false)). 
> 
> However, the output ID `CHEMBL.TARGET:CHEMBL204` is likely something no ARA/KP recognizes. [NodeNorm doesn't resolve this ID.](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=CHEMBL.TARGET:CHEMBL204&conflate=true&drug_chemical_conflate=true&description=false).

If we changed the expected output IDs to `NCBIGene:2147` (primary ID) / `UniProtKB:P00734`, it may end up as a duplicate of Asset 595 (which has its own issue https://github.com/NCATSTranslator/Tests/issues/85).

Should this test be removed as a duplicate?

**Comment by colleenXu** [comment] 2024-07-08 21:12
See https://github.com/NCATSTranslator/Tests/issues/62#issuecomment-2207903878 for latest notes on asset 595

**Comment by maximusunc** [comment] 2024-07-12 17:59
I'm not sure I see why this is a duplicate, but the ID should probably be updated. Putting `UNIPROTKB:P00734` into Name Resolver gives `PR:000051041` which seems to be a subclass of thrombin.

**Comment by maximusunc** [comment] 2024-07-12 18:06
Duplicate of #83

**Closed by maximusunc** 2024-07-12 18:06 UTC
